name: Deploy to VDS

on:
  push:
    branches:
      - master  # Замените на вашу основную ветку

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Укажите версию Node.js, необходимую для вашего проекта

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to VDS
        env:
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
          KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "${{ secrets.SSH_KEY }}" > private_key
          chmod 600 private_key
          ls -la
          rsync -avz --include=".output" --include="ecosystem.config.js" --exclude="*"  -e "ssh -o StrictHostKeyChecking=no -i private_key" ./ $USER@$HOST:/var/www/www-root/data/www/autopilot-taxi.tw1.su/
          ssh -o StrictHostKeyChecking=no -i private_key $USER@$HOST "cd /var/www/www-root/data/www/autopilot-taxi.tw1.su/ && cd .output/server npm install && cd ../.. pm2 restart"
